import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,Download,Music2,TrendingUp,Trophy,CalendarDays,X,ChevronRight,Heart,Target,BarChart3,ListMusic,GitCompare,Home,Plus,Trash2,ArrowLeft,WifiOff}from'lucide-react';
import{ResponsiveContainer,XAxis,YAxis,Tooltip,RadarChart,PolarGrid,PolarAngleAxis,Radar,AreaChart,Area,BarChart,Bar,CartesianGrid,LineChart,Line,Legend}from'recharts';
import'./style.css';import'./mobile.css';import'./features.css';

const METRICS=['音程','安定感','ロングトーン','抑揚','テクニック'];
const MAX={'音程':40,'安定感':30,'ロングトーン':10,'抑揚':15,'テクニック':5};
const fmt=n=>Number(n||0).toFixed(3),day=s=>s?.slice(0,10)||'—',key=x=>`${x.title}|||${x.artist}`;
const pct=(x,k)=>Math.round((x.metrics?.[k]||0)/MAX[k]*100);
const average=(xs,get=x=>x.score)=>xs.length?xs.reduce((s,x)=>s+get(x),0)/xs.length:0;
function useStored(name,initial){const[v,setV]=useState(()=>{try{return JSON.parse(localStorage.getItem(name))??initial}catch{return initial}});useEffect(()=>localStorage.setItem(name,JSON.stringify(v)),[name,v]);return[v,setV]}
function smartMatch(x,query){const tokens=query.trim().split(/\s+/).filter(Boolean),plain=[];for(const t of tokens){let m;if((m=t.match(/^score:(>=|<=|>|<)(\d+(?:\.\d+)?)$/i))){const n=+m[2];if(!({'>':x.score>n,'<':x.score<n,'>=':x.score>=n,'<=':x.score<=n}[m[1]]))return false}else if((m=t.match(/^artist:(.+)$/i))){if(!x.artist.toLowerCase().includes(m[1].toLowerCase()))return false}else if((m=t.match(/^year:(\d{4})$/i))){if(!x.playedAt?.startsWith(m[1]))return false}else if((m=t.match(/^metric:(音程|安定感|ロングトーン|抑揚|テクニック)(>=|<=|>|<)(\d+)$/))){const n=pct(x,m[1]);if(!({'>':n>+m[3],'<':n<+m[3],'>=':n>=+m[3],'<=':n<=+m[3]}[m[2]]))return false}else plain.push(t)}return plain.every(t=>(x.title+' '+x.artist).toLowerCase().includes(t.toLowerCase()))}

function App(){
 const[data,setData]=useState([]),[page,setPage]=useState('home'),[q,setQ]=useState(''),[artist,setArtist]=useState('all'),[month,setMonth]=useState('all'),[sort,setSort]=useState('new'),[view,setView]=useState('all'),[selected,setSelected]=useState(null),[songKey,setSongKey]=useState(null),[sessionDay,setSessionDay]=useState(null),[compare,setCompare]=useState([]),[notice,setNotice]=useState(null);
 const[practice,setPractice]=useStored('karaoke-practice',[]),[goals,setGoals]=useStored('karaoke-goals',[]),[seenIds,setSeenIds]=useStored('karaoke-seen',[]);
 useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/scores.json`).then(r=>r.json()).then(x=>{const scores=x.scores||[];setData(scores);const fresh=scores.filter(s=>!seenIds.includes(s.analysisId));if(seenIds.length&&fresh.length){const bests=fresh.filter(s=>!scores.some(o=>o.analysisId!==s.analysisId&&key(o)===key(s)&&o.score>s.score));setNotice(`${fresh.length}件追加・${bests.length}曲で自己ベスト更新`)}setSeenIds(scores.map(s=>s.analysisId))}).catch(()=>{})},[]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(()=>{})},[]);
 const artists=useMemo(()=>[...new Set(data.map(x=>x.artist))].sort((a,b)=>a.localeCompare(b,'ja')),[data]);
 const months=useMemo(()=>[...new Set(data.map(x=>x.playedAt?.slice(0,7)))].filter(Boolean).sort().reverse(),[data]);
 const songs=useMemo(()=>{const m=new Map;data.forEach(x=>{const k=key(x);if(!m.has(k))m.set(k,[]);m.get(k).push(x)});return[...m.entries()].map(([k,plays])=>({key:k,title:plays[0].title,artist:plays[0].artist,plays:[...plays].sort((a,b)=>a.playedAt.localeCompare(b.playedAt)),best:Math.max(...plays.map(x=>x.score)),avg:average(plays),last:[...plays].sort((a,b)=>b.playedAt.localeCompare(a.playedAt))[0]})).sort((a,b)=>b.last.playedAt.localeCompare(a.last.playedAt))},[data]);
 const sessions=useMemo(()=>{const m=new Map;data.forEach(x=>{const d=day(x.playedAt);if(!m.has(d))m.set(d,[]);m.get(d).push(x)});return[...m.entries()].map(([date,plays])=>{plays.sort((a,b)=>a.playedAt.localeCompare(b.playedAt));const half=Math.ceil(plays.length/2);return{date,plays,avg:average(plays),best:Math.max(...plays.map(x=>x.score)),first:average(plays.slice(0,half)),last:average(plays.slice(half))}}).sort((a,b)=>b.date.localeCompare(a.date))},[data]);
 const filtered=useMemo(()=>data.filter(x=>smartMatch(x,q)&&(artist==='all'||x.artist===artist)&&(month==='all'||x.playedAt?.startsWith(month))&&(view==='all'||view==='90'&&x.score>=90||view==='best'&&x.score===Math.max(...data.filter(y=>key(y)===key(x)).map(y=>y.score)))).sort((a,b)=>sort==='high'?b.score-a.score:sort==='low'?a.score-b.score:sort==='title'?a.title.localeCompare(b.title,'ja'):b.playedAt.localeCompare(a.playedAt)),[data,q,artist,month,sort,view]);
 const stats=useMemo(()=>({avg:average(data),best:data.length?Math.max(...data.map(x=>x.score)):0,unique:songs.length}),[data,songs]);
 const metricAvgs=useMemo(()=>METRICS.map(k=>({name:k,value:average(data,x=>pct(x,k))})).sort((a,b)=>a.value-b.value),[data]);
 const rankings=useMemo(()=>({top:[...songs].sort((a,b)=>b.best-a.best).slice(0,10),artists:[...new Set(data.map(x=>x.artist))].map(a=>{const xs=data.filter(x=>x.artist===a);return{name:a,count:xs.length,avg:average(xs),best:Math.max(...xs.map(x=>x.score))}}).filter(x=>x.count>=2).sort((a,b)=>b.avg-a.avg).slice(0,10),dist:[70,75,80,85,90,95].map(n=>({range:`${n}–${n+4}`,count:data.filter(x=>x.score>=n&&x.score<n+5).length}))}),[data,songs]);
 const selectedSong=songs.find(s=>s.key===songKey),selectedSession=sessions.find(s=>s.date===sessionDay);
 const togglePractice=s=>setPractice(p=>p.includes(s.key)?p.filter(k=>k!==s.key):[...p,s.key]);
 const addGoal=(s,target=90)=>setGoals(g=>g.some(x=>x.key===s.key)?g.map(x=>x.key===s.key?{...x,target}:x):[...g,{key:s.key,title:s.title,artist:s.artist,target}]);
 const exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({scores:data,practice,goals},null,2)],{type:'application/json'}));a.download='karaoke-log.json';a.click()};
 const nav=(p)=>{setPage(p);setSongKey(null);setSessionDay(null);scrollTo({top:0,behavior:'smooth'})};
 return <div className="app"><header><button className="brand brandBtn" onClick={()=>nav('home')}><span><Music2/></span><div><b>KARAOKE LOG</b><small>MY JOYSOUND ARCHIVE</small></div></button><nav>{[['home','概要'],['history','全履歴'],['songs','曲別'],['sessions','歌唱日'],['rankings','分析'],['practice','次回曲'],['goals','目標'],['compare','比較']].map(([k,l])=><button key={k} className={page===k?'active':''} onClick={()=>nav(k)}>{l}</button>)}</nav><div className="actions"><button onClick={exportData}><Download/>書き出し</button></div></header>
 {notice&&<div className="updateNotice"><b>データ更新</b> {notice}<button onClick={()=>setNotice(null)}><X/></button></div>}
 <main className="featureMain">{page==='home'&&<Dashboard data={data} stats={stats} metricAvgs={metricAvgs} sessions={sessions} songs={songs} go={nav}/>} {page==='history'&&<History rows={filtered} q={q} setQ={setQ} artist={artist} setArtist={setArtist} artists={artists} month={month} setMonth={setMonth} months={months} sort={sort} setSort={setSort} view={view} setView={setView} select={setSelected}/>} {page==='songs'&&!selectedSong&&<Songs songs={songs} practice={practice} open={setSongKey} toggle={togglePractice}/>} {page==='songs'&&selectedSong&&<SongPage song={selectedSong} practice={practice} back={()=>setSongKey(null)} toggle={togglePractice} goal={addGoal}/>} {page==='sessions'&&!selectedSession&&<Sessions sessions={sessions} open={setSessionDay}/>} {page==='sessions'&&selectedSession&&<SessionPage session={selectedSession} back={()=>setSessionDay(null)} select={setSelected}/>} {page==='rankings'&&<Rankings rankings={rankings} metricAvgs={metricAvgs}/>} {page==='practice'&&<Practice songs={songs.filter(s=>practice.includes(s.key))} toggle={togglePractice} goal={addGoal} open={s=>{setSongKey(s);setPage('songs')}}/>} {page==='goals'&&<Goals goals={goals} songs={songs} setGoals={setGoals}/>} {page==='compare'&&<Compare data={data} ids={compare} setIds={setCompare}/>} </main>
 <MobileNav page={page} go={nav}/>
 {selected&&<Detail x={selected} close={()=>setSelected(null)} compare={compare} setCompare={setCompare}/>}</div>
}

function Dashboard({data,stats,metricAvgs,sessions,songs,go}){const trend=[...data].sort((a,b)=>a.playedAt.localeCompare(b.playedAt)).slice(-60).map(x=>({date:day(x.playedAt).slice(5),score:x.score}));return <><section className="hero"><div><p className="eyebrow">YOUR SINGING, VISUALIZED.</p><h1>歌声の軌跡を、<br/><em>もっと鮮やかに。</em></h1><p>検索、比較、目標管理まで。カラオケをもっと楽しむための個人アーカイブ。</p></div><div className="heroChart"><div className="chartHead"><span>スコア推移</span><b>{fmt(stats.avg)}<small> 平均</small></b></div><ResponsiveContainer width="100%" height={210}><AreaChart data={trend}><XAxis dataKey="date" hide/><YAxis domain={[70,100]} hide/><Tooltip/><Area dataKey="score" stroke="#f04b51" fill="#f04b5133" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><section className="stats"><Stat icon={<Music2/>} label="総歌唱数" value={data.length} unit="曲"/><Stat icon={<TrendingUp/>} label="平均スコア" value={fmt(stats.avg)} unit="点"/><Stat icon={<Trophy/>} label="最高スコア" value={fmt(stats.best)} unit="点"/><Stat icon={<CalendarDays/>} label="歌った曲" value={stats.unique} unit="曲"/></section><section className="dashboardGrid"><Panel title="伸ばしどころ"><p className="muted">全履歴から見た平均達成率</p>{metricAvgs.map(x=><Meter key={x.name} label={x.name} value={x.value}/>)}</Panel><Panel title="最近の歌唱日">{sessions.slice(0,4).map(s=><button className="miniRow" key={s.date} onClick={()=>go('sessions')}><span>{s.date}<small>{s.plays.length}曲</small></span><b>{fmt(s.avg)}</b><ChevronRight/></button>)}</Panel><Panel title="よく歌う曲">{[...songs].sort((a,b)=>b.plays.length-a.plays.length).slice(0,4).map(s=><div className="miniRow" key={s.key}><span>{s.title}<small>{s.artist}</small></span><b>{s.plays.length}回</b></div>)}</Panel></section></>}
function History({rows,q,setQ,artist,setArtist,artists,month,setMonth,months,sort,setSort,view,setView,select}){return <><PageHead title="全採点履歴" text="通常検索に加え、score:>=90 artist:=LOVE year:2026 metric:安定感<80 のように検索できます。"/><div className="tabs">{[['all','すべて'],['90','90点以上'],['best','自己ベスト']].map(([k,l])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}>{l}</button>)}</div><div className="filters"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="曲名・条件でスマート検索"/></div><select value={artist} onChange={e=>setArtist(e.target.value)}><option value="all">すべてのアーティスト</option>{artists.map(x=><option key={x}>{x}</option>)}</select><select value={month} onChange={e=>setMonth(e.target.value)}><option value="all">すべての期間</option>{months.map(x=><option key={x}>{x.replace('/','年')}月</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">新しい順</option><option value="high">スコアが高い順</option><option value="low">スコアが低い順</option><option value="title">曲名順</option></select></div><div className="table"><div className="tr th"><span>歌唱日</span><span>曲名 / アーティスト</span><span>採点モード</span><span>総合得点</span><span>音程</span><span>安定感</span><span/></div>{rows.map(x=><button className="tr" onClick={()=>select(x)} key={x.analysisId}><span>{day(x.playedAt)}</span><span><b>{x.title}</b><small>{x.artist}</small></span><span><i className="pill">{x.mode}</i></span><span className="score">{fmt(x.score)}</span><span>{pct(x,'音程')}%</span><span>{pct(x,'安定感')}%</span><span><ChevronRight/></span></button>)}</div></>}
const Stat=({icon,label,value,unit})=><article><span>{icon}</span><div><small>{label}</small><b>{value}<i>{unit}</i></b></div></article>;
const Panel=({title,children})=><section className="panel"><h2>{title}</h2>{children}</section>;
const Meter=({label,value})=><div className="meter"><span>{label}</span><div><i style={{width:`${Math.min(100,value)}%`}}/></div><b>{Math.round(value)}%</b></div>;
function PageHead({title,text,back}){return <div className="pageHead">{back&&<button className="back" onClick={back}><ArrowLeft/>戻る</button>}<p className="eyebrow">KARAOKE ARCHIVE</p><h1>{title}</h1>{text&&<p>{text}</p>}</div>}
function Songs({songs,practice,open,toggle}){const[q,setQ]=useState('');const xs=songs.filter(s=>(s.title+s.artist).toLowerCase().includes(q.toLowerCase()));return <><PageHead title="曲ごとの成長" text="同じ曲の記録をまとめて、成長と自己ベストを確認できます。"/><div className="bigSearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="曲名・アーティストで検索"/></div><div className="cardGrid">{xs.map(s=><article className="songCard" key={s.key}><button className={`heart ${practice.includes(s.key)?'on':''}`} onClick={()=>toggle(s)} aria-label="次回歌う曲"><Heart/></button><button className="cardBody" onClick={()=>open(s.key)}><small>{s.artist}</small><h3>{s.title}</h3><div><span>最高 <b>{fmt(s.best)}</b></span><span>平均 <b>{fmt(s.avg)}</b></span><span>{s.plays.length}回</span></div><ChevronRight/></button></article>)}</div></>}
function SongPage({song,practice,back,toggle,goal}){const chart=song.plays.map(x=>({date:day(x.playedAt).slice(5),score:x.score,...Object.fromEntries(METRICS.map(k=>[k,pct(x,k)]))})),gain=song.plays.length>1?song.plays.at(-1).score-song.plays[0].score:0;return <><PageHead back={back} title={song.title} text={song.artist}/><div className="actionBar"><button className={practice.includes(song.key)?'primary':''} onClick={()=>toggle(song)}><Heart/> {practice.includes(song.key)?'次回リスト登録済み':'次回歌う'}</button><button onClick={()=>goal(song,90)}><Target/>90点を目標にする</button></div><section className="stats compact"><Stat icon={<Trophy/>} label="自己ベスト" value={fmt(song.best)} unit="点"/><Stat icon={<TrendingUp/>} label="平均" value={fmt(song.avg)} unit="点"/><Stat icon={<Music2/>} label="歌唱回数" value={song.plays.length} unit="回"/><Stat icon={<BarChart3/>} label="初回から" value={`${gain>=0?'+':''}${fmt(gain)}`} unit="点"/></section><Panel title="スコア成長"><div className="chartTall"><ResponsiveContainer><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis domain={['dataMin - 2','dataMax + 2']}/><Tooltip/><Line dataKey="score" stroke="#ef474f" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Panel><Panel title="各項目の推移"><div className="chartTall"><ResponsiveContainer><LineChart data={chart}><XAxis dataKey="date"/><YAxis domain={[50,100]}/><Tooltip/><Legend/>{METRICS.map((k,i)=><Line key={k} dataKey={k} stroke={['#ef474f','#4e79a7','#59a14f','#f28e2b','#af7aa1'][i]} dot={false}/>)}</LineChart></ResponsiveContainer></div></Panel><Panel title="歌唱履歴">{[...song.plays].reverse().map(x=><div className="miniRow" key={x.analysisId}><span>{x.playedAt}<small>{x.mode}</small></span><b>{fmt(x.score)}</b></div>)}</Panel></>}
function Sessions({sessions,open}){return <><PageHead title="歌唱日レポート" text="カラオケに行った日ごとの成績と、後半の変化を振り返れます。"/><div className="cardGrid sessions">{sessions.map(s=><button className="sessionCard" key={s.date} onClick={()=>open(s.date)}><CalendarDays/><div><h3>{s.date}</h3><span>{s.plays.length}曲</span></div><b>{fmt(s.avg)}<small>平均</small></b><ChevronRight/></button>)}</div></>}
function SessionPage({session,back,select}){const chart=session.plays.map((x,i)=>({n:i+1,score:x.score,title:x.title}));return <><PageHead back={back} title={session.date} text={`${session.plays.length}曲を歌唱`}/><section className="stats compact"><Stat icon={<TrendingUp/>} label="平均" value={fmt(session.avg)} unit="点"/><Stat icon={<Trophy/>} label="最高" value={fmt(session.best)} unit="点"/><Stat icon={<Home/>} label="前半平均" value={fmt(session.first)} unit="点"/><Stat icon={<CalendarDays/>} label="後半平均" value={fmt(session.last)} unit="点"/></section><Panel title="当日のスコア推移"><div className="chartTall"><ResponsiveContainer><LineChart data={chart}><XAxis dataKey="n"/><YAxis domain={[70,100]}/><Tooltip/><Line dataKey="score" stroke="#ef474f" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Panel><Panel title="セットリスト">{session.plays.map((x,i)=><button className="miniRow" key={x.analysisId} onClick={()=>select(x)}><em>{i+1}</em><span>{x.title}<small>{x.artist} · {x.playedAt.slice(11)}</small></span><b>{fmt(x.score)}</b><ChevronRight/></button>)}</Panel></>}
function Rankings({rankings,metricAvgs}){return <><PageHead title="分析とランキング" text="得点分布、歴代ベスト、得意・苦手をまとめて確認できます。"/><div className="dashboardGrid rankGrid"><Panel title="スコア分布"><div className="chartTall"><ResponsiveContainer><BarChart data={rankings.dist}><XAxis dataKey="range"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#ef474f"/></BarChart></ResponsiveContainer></div></Panel><Panel title="項目別の得意・苦手">{metricAvgs.map(x=><Meter key={x.name} label={x.name} value={x.value}/>)}</Panel><Panel title="歴代ベスト10"><ol className="ranking">{rankings.top.map(s=><li key={s.key}><span>{s.title}<small>{s.artist}</small></span><b>{fmt(s.best)}</b></li>)}</ol></Panel><Panel title="アーティスト別平均"><ol className="ranking">{rankings.artists.map(s=><li key={s.name}><span>{s.name}<small>{s.count}回</small></span><b>{fmt(s.avg)}</b></li>)}</ol></Panel></div></>}
function Practice({songs,toggle,goal,open}){return <><PageHead title="次回歌う曲" text="カラオケ当日にそのまま使える再挑戦リストです。"/>{!songs.length?<Empty text="曲別ページのハートから追加できます"/>:<div className="practiceList">{songs.map(s=>{const gap=Math.max(0,90-s.best);return <article key={s.key}><button className="cardBody" onClick={()=>open(s.key)}><span><small>{s.artist}</small><h3>{s.title}</h3></span><span className="challenge">最高 {fmt(s.best)}<small>{gap?`90点まであと ${fmt(gap)}`:'90点達成済み'}</small></span></button><button onClick={()=>goal(s,Math.ceil(s.best+1))}><Target/>目標</button><button onClick={()=>toggle(s)}><Trash2/></button></article>})}</div>}</>}
function Goals({goals,songs,setGoals}){const[choice,setChoice]=useState(''),[target,setTarget]=useState(90);const add=()=>{const s=songs.find(x=>x.key===choice);if(s)setGoals(g=>[...g.filter(x=>x.key!==s.key),{key:s.key,title:s.title,artist:s.artist,target:+target}])};return <><PageHead title="目標管理" text="曲ごとの目標点と達成状況を管理します。"/><div className="goalForm"><select value={choice} onChange={e=>setChoice(e.target.value)}><option value="">曲を選択</option>{songs.map(s=><option value={s.key} key={s.key}>{s.title} / {s.artist}</option>)}</select><input type="number" min="70" max="100" step="0.001" value={target} onChange={e=>setTarget(e.target.value)}/><button className="primary" onClick={add}><Plus/>追加</button></div>{!goals.length?<Empty text="上のフォームから目標を追加できます"/>:<div className="goalList">{goals.map(g=>{const s=songs.find(x=>x.key===g.key),best=s?.best||0,done=best>=g.target;return <article className={done?'done':''} key={g.key}><Target/><div><h3>{g.title}</h3><small>{g.artist}</small><Meter label={done?'達成！':`あと ${fmt(g.target-best)}点`} value={Math.min(100,best/g.target*100)}/></div><b>{fmt(best)}<small>/ {fmt(g.target)}</small></b><button onClick={()=>setGoals(x=>x.filter(y=>y.key!==g.key))}><Trash2/></button></article>})}</div>}</>}
function Compare({data,ids,setIds}){const chosen=ids.map(id=>data.find(x=>x.analysisId===id)).filter(Boolean);const set=(i,v)=>setIds(x=>i===0?[v,x[1]].filter(Boolean):[x[0],v].filter(Boolean));return <><PageHead title="採点結果を比較" text="2回分を横並びにして、伸びた項目を確認できます。"/><div className="comparePick"><select value={ids[0]||''} onChange={e=>set(0,e.target.value)}><option value="">1件目を選択</option>{data.map(x=><option key={x.analysisId} value={x.analysisId}>{x.playedAt}｜{x.title}｜{fmt(x.score)}</option>)}</select><GitCompare/><select value={ids[1]||''} onChange={e=>set(1,e.target.value)}><option value="">2件目を選択</option>{data.map(x=><option key={x.analysisId} value={x.analysisId}>{x.playedAt}｜{x.title}｜{fmt(x.score)}</option>)}</select></div>{chosen.length===2?<div className="compareTable"><div/><h3>{chosen[0].title}<small>{chosen[0].playedAt}</small></h3><h3>{chosen[1].title}<small>{chosen[1].playedAt}</small></h3>{[['総合点',chosen[0].score,chosen[1].score],...METRICS.map(k=>[k,pct(chosen[0],k),pct(chosen[1],k)])].map(([l,a,b])=><React.Fragment key={l}><b>{l}</b><span>{fmt(a)}</span><span className={b>a?'up':b<a?'down':''}>{fmt(b)} <small>{b>a?`+${fmt(b-a)}`:b<a?fmt(b-a):'±0'}</small></span></React.Fragment>)}</div>:<Empty text="比較する履歴を2件選択してください"/>}</>}
function Empty({text}){return <div className="emptyState"><WifiOff/><p>{text}</p></div>}
function MobileNav({page,go}){return <div className="mobileNav">{[['home',Home,'概要'],['history',Search,'履歴'],['songs',Music2,'曲別'],['practice',ListMusic,'次回曲'],['goals',Target,'目標']].map(([k,I,l])=><button className={page===k?'active':''} key={k} onClick={()=>go(k)}><I/><span>{l}</span></button>)}</div>}
function Detail({x,close,compare,setCompare}){const add=()=>{setCompare(ids=>ids.includes(x.analysisId)?ids.filter(id=>id!==x.analysisId):[...ids.slice(-1),x.analysisId]);close()};return <div className="overlay" onClick={close}><aside onClick={e=>e.stopPropagation()}><button className="close" aria-label="閉じる" onClick={close}><X/></button><p className="eyebrow">SCORE DETAIL</p><h2>{x.title}</h2><p className="artist">{x.artist} · {x.playedAt}</p><button className={compare.includes(x.analysisId)?'primary compareAdd':'compareAdd'} onClick={add}><GitCompare/>比較に追加</button><div className="bigScore"><small>総合得点</small><b>{fmt(x.score)}</b><span>点</span></div><div className="radar"><ResponsiveContainer width="100%" height={250}><RadarChart outerRadius="65%" data={METRICS.map(k=>({name:k,value:pct(x,k)}))}><PolarGrid/><PolarAngleAxis dataKey="name"/><Radar dataKey="value" stroke="#ef474f" fill="#ef474f" fillOpacity=".25"/></RadarChart></ResponsiveContainer></div><div className="metricList">{METRICS.map(k=><div key={k}><span>{k}</span><div><i style={{width:`${pct(x,k)}%`}}/></div><b>{fmt(x.metrics?.[k])}<small> / {MAX[k]}</small></b></div>)}</div><div className="tech"><span>AIボーナス <b>{fmt(x.aiBonus)}</b></span><span>こぶし <b>{x.techniques?.こぶし||0}</b></span><span>しゃくり <b>{x.techniques?.しゃくり||0}</b></span><span>ビブラート <b>{x.techniques?.ビブラート||0}</b></span></div></aside></div>}
createRoot(document.getElementById('root')).render(<App/>);
