import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,Download,Music2,TrendingUp,Trophy,CalendarDays,X,ChevronRight}from'lucide-react';import{ResponsiveContainer,XAxis,YAxis,Tooltip,RadarChart,PolarGrid,PolarAngleAxis,Radar,AreaChart,Area}from'recharts';import'./style.css';
const METRICS=['音程','安定感','ロングトーン','抑揚','テクニック'],MAX={'音程':40,'安定感':30,'ロングトーン':10,'抑揚':15,'テクニック':5};
const fmt=n=>Number(n||0).toFixed(3),date=s=>s?.slice(0,10)||'—';
function App(){const[data,setData]=useState([]),[q,setQ]=useState(''),[artist,setArtist]=useState('all'),[month,setMonth]=useState('all'),[sort,setSort]=useState('new'),[selected,setSelected]=useState(null),[view,setView]=useState('all');const load=()=>fetch(`${import.meta.env.BASE_URL}data/scores.json`).then(r=>r.json()).then(x=>setData(x.scores||[]));useEffect(()=>{load().catch(()=>{})},[]);
const artists=useMemo(()=>[...new Set(data.map(x=>x.artist))].sort((a,b)=>a.localeCompare(b,'ja')), [data]);const months=useMemo(()=>[...new Set(data.map(x=>x.playedAt?.slice(0,7)))].filter(Boolean).sort().reverse(),[data]);
const filtered=useMemo(()=>data.filter(x=>(x.title+x.artist).toLowerCase().includes(q.toLowerCase())&&(artist==='all'||x.artist===artist)&&(month==='all'||x.playedAt?.startsWith(month))&&(view==='all'||view==='90'&&x.score>=90||view==='best'&&x.score===Math.max(...data.filter(y=>y.title===x.title).map(y=>y.score)))).sort((a,b)=>sort==='high'?b.score-a.score:sort==='low'?a.score-b.score:sort==='title'?a.title.localeCompare(b.title,'ja'):String(b.playedAt).localeCompare(String(a.playedAt))),[data,q,artist,month,sort,view]);
const avg=data.length?data.reduce((s,x)=>s+x.score,0)/data.length:0,best=data.length?Math.max(...data.map(x=>x.score)):0,unique=new Set(data.map(x=>x.title)).size;const trend=[...data].sort((a,b)=>String(a.playedAt).localeCompare(String(b.playedAt))).map(x=>({date:date(x.playedAt).slice(5),score:x.score,title:x.title}));
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),count:data.length,scores:data},null,2)],{type:'application/json'}));a.download='joysound-scores.json';a.click();URL.revokeObjectURL(a.href)}
return <div className="app"><header><div className="brand"><span><Music2/></span><div><b>KARAOKE LOG</b><small>MY JOYSOUND ARCHIVE</small></div></div><nav><button className="active">ダッシュボード</button><button onClick={()=>document.querySelector('#history').scrollIntoView()}>全履歴</button></nav><div className="actions"><button onClick={download}><Download/>書き出し</button></div></header><main>
<section className="hero"><div><p className="eyebrow">YOUR SINGING, VISUALIZED.</p><h1>歌声の軌跡を、<br/><em>もっと鮮やかに。</em></h1><p>JOYSOUNDの採点履歴を、探せて、比べて、振り返れる。<br/>あなた専用のカラオケ・アーカイブ。</p></div><div className="heroChart"><div className="chartHead"><span>スコア推移</span><b>{fmt(avg)}<small> 平均</small></b></div><ResponsiveContainer width="100%" height={210}><AreaChart data={trend.slice(-60)}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#f04b51" stopOpacity=".35"/><stop offset="1" stopColor="#f04b51" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="date" hide/><YAxis domain={[70,100]} hide/><Tooltip/><Area dataKey="score" stroke="#f04b51" fill="url(#g)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section>
<section className="stats"><article><span><Music2/></span><div><small>総歌唱数</small><b>{data.length}<i>曲</i></b></div></article><article><span><TrendingUp/></span><div><small>平均スコア</small><b>{fmt(avg)}<i>点</i></b></div></article><article><span><Trophy/></span><div><small>最高スコア</small><b>{fmt(best)}<i>点</i></b></div></article><article><span><CalendarDays/></span><div><small>歌った曲</small><b>{unique}<i>曲</i></b></div></article></section>
<section className="history" id="history"><div className="sectionHead"><div><p className="eyebrow">SCORE ARCHIVE</p><h2>採点履歴</h2></div><div className="tabs">{[['all','すべて'],['90','90点以上'],['best','自己ベスト']].map(([k,l])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}>{l}</button>)}</div></div><div className="filters"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="曲名・アーティストで検索"/></div><select value={artist} onChange={e=>setArtist(e.target.value)}><option value="all">すべてのアーティスト</option>{artists.map(x=><option key={x}>{x}</option>)}</select><select value={month} onChange={e=>setMonth(e.target.value)}><option value="all">すべての期間</option>{months.map(x=><option key={x}>{x.replace('/','年')}月</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">新しい順</option><option value="high">スコアが高い順</option><option value="low">スコアが低い順</option><option value="title">曲名順</option></select></div>
<div className="table"><div className="tr th"><span>歌唱日</span><span>曲名 / アーティスト</span><span>採点モード</span><span>総合得点</span><span>音程</span><span>安定感</span><span></span></div>{filtered.map(x=><button className="tr" onClick={()=>setSelected(x)} key={x.analysisId}><span>{date(x.playedAt).replaceAll('-','.')}</span><span><b>{x.title}</b><small>{x.artist}</small></span><span><i className="pill">{x.mode||'分析採点'}</i></span><span className="score">{fmt(x.score)}</span><span>{x.metrics?.音程?Math.round(x.metrics.音程/MAX.音程*100)+'%':'—'}</span><span>{x.metrics?.安定感?Math.round(x.metrics.安定感/MAX.安定感*100)+'%':'—'}</span><span><ChevronRight/></span></button>)}{!filtered.length&&<div className="empty">該当する履歴がありません</div>}</div></section></main>
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><aside onClick={e=>e.stopPropagation()}><button className="close" aria-label="閉じる" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">SCORE DETAIL</p><h2>{selected.title}</h2><p className="artist">{selected.artist} · {selected.playedAt}</p><div className="bigScore"><small>総合得点</small><b>{fmt(selected.score)}</b><span>点</span></div><div className="radar"><ResponsiveContainer width="100%" height={270}><RadarChart data={METRICS.map(k=>({name:k,value:(selected.metrics?.[k]||0)/MAX[k]*100,fullMark:100}))}><PolarGrid/><PolarAngleAxis dataKey="name"/><Radar dataKey="value" stroke="#ef474f" fill="#ef474f" fillOpacity=".25"/></RadarChart></ResponsiveContainer></div><div className="metricList">{METRICS.map(k=><div key={k}><span>{k}</span><div><i style={{width:`${(selected.metrics?.[k]||0)/MAX[k]*100}%`}}/></div><b>{fmt(selected.metrics?.[k])}<small> / {MAX[k]}</small></b></div>)}</div><div className="tech"><span>AIボーナス <b>{fmt(selected.aiBonus)}</b></span><span>こぶし <b>{selected.techniques?.こぶし||0}</b></span><span>しゃくり <b>{selected.techniques?.しゃくり||0}</b></span><span>ビブラート <b>{selected.techniques?.ビブラート||0}</b></span></div></aside></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
